// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALhlh20SYg09yAIK_xRycfjIyjSjwuU90',
    appId: '1:499093328449:android:2ad79d4544bb6b66baecc0',
    messagingSenderId: '499093328449',
    projectId: 'gigateaminventory',
    storageBucket: 'gigateaminventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhM393dsEa2MdvQm3zyRppjL9_DArWm5g',
    appId: '1:499093328449:ios:44fba788170af9e3baecc0',
    messagingSenderId: '499093328449',
    projectId: 'gigateaminventory',
    storageBucket: 'gigateaminventory.firebasestorage.app',
    iosBundleId: 'com.gigateam.gigateamInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNlvOtahtmh88GC_H1HrOxfbiYjvHtSqQ',
    appId: '1:499093328449:web:6e1199867312b8c4baecc0',
    messagingSenderId: '499093328449',
    projectId: 'gigateaminventory',
    authDomain: 'gigateaminventory.firebaseapp.com',
    storageBucket: 'gigateaminventory.firebasestorage.app',
  );
}
